name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        npm run test:ci
    - name: Save artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage/angular-themes-blog-post
